"""Panel settings, read once at startup from config.env.

config.env sits next to app.py in the panel directory (see install.sh). The
runtime files the panel creates for itself are kept in that same directory.
"""

import os

import bcrypt

from .log import logger

# Panel directory: the one holding app.py, config.env and the runtime files.
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def load_env(path="config.env"):
    env = {}
    if not os.path.exists(path):
        return env
    with open(path) as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            if "=" in line:
                key, _, val = line.partition("=")
                env[key.strip()] = val.strip().strip('"').strip("'")
    return env


def _resolve_password_hash(env):
    """Backwards-compatible password handling: prefer the bcrypt hash; if only
    the plaintext PANEL_PASSWORD is set (old configs), hash it in-memory."""
    password_hash = env.get("PANEL_PASSWORD_HASH", "").strip()
    legacy_plaintext = env.get("PANEL_PASSWORD", "").strip()
    if not password_hash and legacy_plaintext:
        password_hash = bcrypt.hashpw(legacy_plaintext.encode(), bcrypt.gensalt()).decode()
        logger.warning("config.env uses legacy plaintext PANEL_PASSWORD. "
                       "Re-run install.sh --update or replace it with PANEL_PASSWORD_HASH=...")
    if not password_hash:
        password_hash = bcrypt.hashpw(b"changeme", bcrypt.gensalt()).decode()
        logger.warning("no panel password set. Defaulting to 'changeme'.")
    return password_hash


_env = load_env(os.path.join(BASE_DIR, "config.env"))

PANEL_PASSWORD_HASH = _resolve_password_hash(_env)
PANEL_PORT     = int(_env.get("PANEL_PORT", 8888))
# Address the panel listens on. install.sh sets 127.0.0.1 when nginx serves
# the panel on a domain, so it can't be reached around nginx.
PANEL_HOST     = _env.get("PANEL_HOST", "").strip() or "0.0.0.0"
# Set when every request comes through a reverse proxy on this machine: the
# client address and scheme are then read from the headers it adds.
PANEL_BEHIND_PROXY = _env.get("PANEL_BEHIND_PROXY", "").strip().lower() in ("1", "true", "yes")
if PANEL_BEHIND_PROXY and PANEL_HOST not in ("127.0.0.1", "localhost", "::1"):
    logger.warning("PANEL_BEHIND_PROXY is set but the panel listens on %s: clients reaching it "
                   "directly can fake their address. Set PANEL_HOST=127.0.0.1.", PANEL_HOST)
SERVER_DIR     = _env.get("SERVER_DIR",    "/home/arma/server")
SERVER_CONFIG  = _env.get("SERVER_CONFIG", "/home/arma/server/config.json")
LOG_DIR        = _env.get("LOG_DIR",       "/home/arma/.config/ArmaReforger/logs")
WORKSHOP_DIR   = _env.get("WORKSHOP_DIR",  "/home/arma/.config/ArmaReforger/addons")
# Where Reforger writes session saves. The real layout produced by the server
# under install.sh defaults is `{LOG_DIR_parent}/profile/.save/`, e.g.
# `/home/arma/.config/ArmaReforger/profile/.save/{game,playersave,settings}/`.
# Override with PROFILE_DIR in config.env if your install differs.
PROFILE_DIR    = _env.get(
    "PROFILE_DIR",
    os.path.join(os.path.dirname(LOG_DIR.rstrip("/")) or "/home/arma/.config/ArmaReforger", "profile"),
)
MAX_FPS        = _env.get("MAX_FPS", "").strip()

# Files generated by the panel itself (ignored by git).
SECRET_FILE       = os.path.join(BASE_DIR, ".panel-secret")
SCAN_CACHE_FILE   = os.path.join(BASE_DIR, ".scenario-cache.json")
CONFIG_BACKUP_DIR = os.path.join(BASE_DIR, "config-backups")
MODSETS_DIR       = os.path.join(BASE_DIR, "modsets")
SETTINGS_FILE     = os.path.join(BASE_DIR, "panel-settings.json")
